const grupos = [
  {
    nomeGrupo: "Família Braz",
    membros: [
      { nome: "Carlinhos", data: "1999-01-16", descricao: "está em uma mensagem para mandar para o grupo da familia, nascida em 1999-01-16 (inclui um dado historico interessante deste dia) ótimo mecânico desde criança. Filho da Cris" },
      { nome: "Olavo(vô)/Maria (Vó)", data: "1930-01-28", descricao: "está em uma mensagem para mandar para o grupo da familia, nascida em 1930-01-28 (inclui um dado historico interessante deste dia) Meu vô e minha vó já falecidos, nasceram no mesmo dia tem a mesma idade. Comemoram mais de 50 anos de casados, muito católicos e muito reconhecido pela comunidade da igreja, sempre por ajudar bastante as pessoas" },
      { nome: "Paula", data: "1985-01-30", descricao: "está em uma mensagem para mandar para o grupo da familia, nascida em 1985-01-30 (inclui um dado historico interessante deste dia) Professora de yoga, nerd, adora animes e RPG, na arvore genealógica da familia Braz é neta e filha da Cristina, mãe da Kaia " },
      { nome: "Luca Toni", data: "2023-02-06", descricao: "está em uma mensagem para mandar para o grupo da familia,nascida em 2023-02-06 (inclui um dado historico interessante deste dia) Um dos membros mais novos da família, ja faz aula de música, de natação, come extremamente saudavel. Bisneto, Filho do Leon com a Samanda" },
      { nome: "Gabrielle", data: "1996-02-08", descricao: "está em uma mensagem para mandar para o grupo da familia, nascida em 1996-02-08 (inclui um dado historico interessante deste dia), Engenheira Mecanica, Engenheira Eletrica, gosta de jogar bola. Neta, filha do Celso com" },
      { nome: "Domingos", data: "1957-02-12", descricao: "está em uma mensagem para mandar para o grupo da familia, nascida em 1957-02-12 (inclui um dado historico interessante deste dia), Domingos trabalhava no hospital da mulher, faleceu por conta de problemas com alcool, queria uma mensagem bonita pois era uma pessoa extremamente boa. Filho, Pai de gemeas." },
      { nome: "Lourdinha", data: "1958-03-04", descricao: "está em uma mensagem para mandar para o grupo da familia, nascida em 1958-03-04 (inclui um dado historico interessante deste dia), Psicologa, única das filhas que voltou para minas, trabalhava na APAE. Mãe do Oto, Igor e Julia (gemeos)" },
      { nome: "Adilson", data: "1964-03-06", descricao: "está em uma mensagem para mandar para o grupo da familia, nascida em 1964-03-06 (inclui um dado historico interessante deste dia), namorado de Marta, chegou na familia a não tanto tempo e está fazendo muito bem a ela" },
      { nome: "Oto", data: "1994-03-09", descricao: "está em uma mensagem para mandar para o grupo da familia, nascida em 1994-03-09 (inclui um dado historico interessante deste dia), fala Koreano, timido, caseiro. Neto e Filho mais velho da Lourdinha" },
      { nome: "Celso", data: "1965-03-10", descricao: "está em uma mensagem para mandar para o grupo da familia, nascida em 1965-03-10 (inclui um dado historico interessante deste dia), Baixinho, muito trabalhador, um icone na igreja. Pai do Mateus e da Gabrielle" },
      { nome: "Marcio", data: "1967-03-13", descricao: "está em uma mensagem para mandar para o grupo da familia, nascida em 1967-03-13 (inclui um dado historico interessante deste dia), Mais conhecido como aranha, gosta de jogar bola, basquete, volei, ama viajar, já está velho mais acha que tem 20 anos. Filho mais novo dos meus avós" },
      { nome: "Daniel", data: "1981-04-08", descricao: "está em uma mensagem para mandar para o grupo da familia, nascida em 1981-04-08 (inclui um dado historico interessante deste dia), formado em Agronomia, concursado no mapa e agora desenvolvedor de software no mercado livre também, muito ingeligente. Filho da Lucia com Carlos e irmão mais velho, Pai de duas linas filhas com a Jaque" },
      { nome: "Caue", data: "2017-05-06", descricao: "está em uma mensagem para mandar para o grupo da familia, nascida em 2017-05-06 (inclui um dado historico interessante deste dia), , filho do Carlinhos, neto da Cris" },
      { nome: "Cecília", data: "1964-05-09", descricao: "está em uma mensagem para mandar para o grupo da familia, nascida em 1964-05-09 (inclui um dado historico interessante deste dia) Militante, esquerdista, Marxista, luta pelo direitos e igualdade e por uma revolução comunista, adora cachorros e gatos, professora de historia. Mãe do Vitor" },
      { nome: "Kaia", data: "2017-05-09", descricao: "está em uma mensagem para mandar para o grupo da familia, nascida em 2017-05-09 (inclui um dado historico interessante deste dia) Pequena, novinha, morou no uruguai fala espanhol, faz Taekendo, adora brincar na rua. Bisneta, Filha da Paula" },
      { nome: "Jaque", data: "2025-05-27", descricao: "está em uma mensagem para mandar para o grupo da familia, nascida em 2025-05-27 (inclui um dado historico interessante deste dia) Formada em educação fisica, trabalha na uff. Casada com Daniel e tem duas lindas filhas" },
      { nome: "Hugo", data: "1983-06-14", descricao: "está em uma mensagem para mandar para o grupo da familia, nascida em 1983-06-14(inclui um dado historico interessante deste dia) , Conhecido como Toxa pelo cabelo ruivo, Flamenguista, formado em Ciência da computação, desenvolvedor, adora cerveja artesanal. Neto, Pai do Pedro " },
      { nome: "Cris", data: "1979-06-22", descricao: "está em uma mensagem para mandar para o grupo da familia, nascida em 1979-06-22 (inclui um dado historico interessante deste dia), Trabalha no meio cultural, organiza eventos junto ao Marido. Casada com Xan, Mãe do Carlinhos e Bernardo " },
      { nome: "Maria Alice", data: "2023-06-25", descricao: "está em uma mensagem para mandar para o grupo da familia, nascida em 2023-06-25 (inclui um dado historico interessante deste dia),  Bisneta da familia, Filha do Daniel com a jaque, irmã mais velha" },
      { nome: "Rosélia", data: "1963-07-04", descricao: "está em uma mensagem para mandar para o grupo da familia, nascida em 1963-07-04 (inclui um dado historico interessante deste dia),  Contadora de muitos anos, entende tudo da área, adora viajar, muito carismática um icone da igreja catolica. Casada com Celso e Mãe do Matheus e da Gabrielle" },
      { nome: "Bernardo", data: "2010-07-09", descricao: "está em uma mensagem para mandar para o grupo da familia, nascida em 2010-07-09 (inclui um dado historico interessante deste dia),  Novo, desenha muito bem, faz ótima caricaturas, tem creatividade incrível, conhecido como Bê. Bisneto, filho do Xan com a Cris" },
      { nome: "Igor", data: "1997-07-19", descricao: "está em uma mensagem para mandar para o grupo da familia, nascida em 1997-07-19 (inclui um dado historico interessante deste dia), Formado em Arquitetura porém nunca atuou na área, virou nômade viajante, pega estrada a fora, ja trabalhou em diversas ONGS, já mochilou em cada canto deste Brasil, até argentina, trabalhou em cozinha de cruzeiro e ama esta vida. Neto e gemêos da Júlia e irmão mais novo do Oto, Filho da Lourdinha" },
      { nome: "Júlia", data: "1997-07-19", descricao: "está em uma mensagem para mandar para o grupo da familia, nascida em 1997-07-19 (inclui um dado historico interessante deste dia), Mineira, quetinha, caseira, gosta de ficar em casa, jogando jogos de internet e amizades online. Neta irmão gemea do Igor e irmã mais nova do Oto, filho de Lourdinha com Cazuza" },      
      { nome: "Cazuza", data: "1962-08-05", descricao: "está em uma mensagem para mandar para o grupo da familia, nascida em 1962-08-05 (inclui um dado historico interessante deste dia), Mineiro, pau para toda obra, gente boa, gosta de uma conversa, porém turrão ninguém muda opinião desse cara, dificil convence-lo de qualquer coisa =). Casado com a Lourdinha, pai de Oto e dos gemeos Igor e Júlia, Casado com a Lourdinha " },
      { nome: "Olário ", data: "1995-08-15", descricao: "está em uma mensagem para mandar para o grupo da familia, nascida em 1995-08-15 (inclui um dado historico interessante deste dia), Namorado do Matheus, ainda com pouco contato com familia pois mora longe, não tenho muitas informações sobre Olário " },
      { nome: "Alexandre", data: "1974-08-16", descricao: "está em uma mensagem para mandar para o grupo da familia, nascida em 1974-08-16 (inclui um dado historico interessante deste dia), Formado em comunicação, mais conhecido como Xan, Produtor de eventos músicais desde novo, trabalha em diversos eventos culturais, principalmente de rock, já fundou bar famoso para os rockeiros chamado Submundo, sempre esteve envolvido neste meio, cultural, do rock, samba, adorador de uma boa cerveja, sempre vai embora cedo dos rolês de familia pq sempre tem compromisso, Tem a famosa frase 'sua vez' porém nunca é a vez dele de pegar cerveja. Neto mais velho, pai do Bernanrdo com a Cris " },
      { nome: "Matheus ", data: "1991-08-26", descricao: "está em uma mensagem para mandar para o grupo da familia, nascida em 1991-08-26 (inclui um dado historico interessante deste dia), Formado em gastronomia, trabalha em uma das cidades mais movimentadas do ramo gastronomico, porém não é cheff de cozinha, trabalha em partes adminstrativas dos restaurantes (familia toda achando que ele cozinhava hahah). Neto, irmão da Gabrielle, filho do Celso com a Rosélia" },
      { nome: "Giselle", data: "1985-06-25", descricao: "está em uma mensagem para mandar para o grupo da familia, nascida em 1985-06-25 (inclui um dado historico interessante deste dia), Economista, trabalha em uma multinacional a anos, Ama viajar, divertida, gosta de conversa, churrasco. Casada com Marcio" },
      { nome: "Leon", data: "1989-08-16", descricao: "está em uma mensagem para mandar para o grupo da familia, nascida em 1989-08-16 (inclui um dado historico interessante deste dia), Ama trabalhar, Engenheiro automação industrial, ja faz quase 15 anos na mesma empresa e única até hoje, Gosta de politica, viajar, ama cerveja sabe fazer uma deliciosa IPA. Neto, irmão da Paula e gemeo da Luiza, filho da Cristina, casado com Samanda, pai do Luca Toni e está vindo uma nova membra da familia já já" },
      { nome: "Luiza", data: "1989-08-16", descricao: "está em uma mensagem para mandar para o grupo da familia, nascida em 1989-08-16 (inclui um dado historico interessante deste dia), Professora ensino fundamental, Formada em Biologia, já trabalhou maternal, de esquerda, gosta da natureza, viajar. Neta, filha da Cristina, irmã da Paula e gemea do Leon" },
      { nome: "Samanda", data: "1991-10-04", descricao: "está em uma mensagem para mandar para o grupo da familia, nascida em 1991-10-04 (inclui um dado historico interessante deste dia), Formada em Engenharia Elétrica, alegre, come extremamente bem, atos muito saúdaveis. Casada com Leon, mãe do Luca Tonni e uma nova menininha a caminho" },
      { nome: "Vitor", data: "1990-10-23", descricao: "está em uma mensagem para mandar para o grupo da familia, nascida em 1990-10-23 (inclui um dado historico interessante deste dia), Formado em Ciência da computação, desenvolvedor de software, gosta de praticar esporte, ja jogou bola futebol americano, volei e hoje joga tennis, gosta de boardgame, cerveja e reunir com os amigos. Neto, filho da Cecília" },
      { nome: "Lúcia ", data: "1960-10-27", descricao: "está em uma mensagem para mandar para o grupo da familia, nascida em 1960-10-27 (inclui um dado historico interessante deste dia), Professora, porém se formou em direito e trabalhou no forum da cidade por muitos anos. Adora festejar, reunir amigos, familia no sitio, Tem grupo de caminhadas longas. Filha, mãe do Daniel e do Rafael" },
      { nome: "Cristina ", data: "1961-10-28", descricao: "está em uma mensagem para mandar para o grupo da familia, nascida em 1961-10-28 (inclui um dado historico interessante deste dia), Professora, formada em geografia, adora festejar, ir em baile, dançar. Filha e mãe da Paula e dos gemeos Leon e Luiza" },
      { nome: "Marta ", data: "1962-10-29", descricao: "está em uma mensagem para mandar para o grupo da familia, nascida em 1962-10-29 (inclui um dado historico interessante deste dia), Dedicou muito a vida a cuidar do pai dela, nosso querido Vô Olavo, sempre muito participativa na paroquia da igreja. Filha namorada do Adilson" }      
    ]
  },
  {
    nomeGrupo: "Adelaide 🐶🐾💖",
    membros: [
      { nome: "Adelaide", data: "2025-06-11", descricao: "nossa cachorrinha, 3 meses de vida, 1 mes com a gente, está com cinomose e estamos fazendo de tudo para salva-la" }
    ]
  }
];

export function aniversariantesPorGrupoHoje() {
  const hoje = new Date().toLocaleDateString('pt-BR').slice(0, 5); // "dd/MM"
  const hojeFormatado = hoje.split('/').reverse().join('-'); // "MM-DD"

  return grupos.map(grupo => ({
    nomeGrupo: grupo.nomeGrupo,
    aniversariantes: grupo.membros.filter(p => p.data.slice(5, 10) === hojeFormatado)
  })).filter(g => g.aniversariantes.length > 0);
}